name = "LabMaze"
uuid = "bba4e509-098c-4c3e-9e4f-ff6e34834d9e"
authors = ["Ta-Chu Kao <tachu.kao@gmail.com>"]
version = "0.1.0"

[deps]
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
GraphPlot = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
